<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImDzqAk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImDzqAk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerImDzqAk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerImDzqAk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerImDzqAk\App_KernelDevDebugContainer([
    'container.build_hash' => 'ImDzqAk',
    'container.build_id' => 'eec8b69f',
    'container.build_time' => 1644493207,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImDzqAk');
