name: Afadima

on: [push]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker-compose build .
          docker-compose build .
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/afadima-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/afadima-backend:latest    
